version: 2

models:
  - name: stg_customers
    description: Staged customer data from Snowflake.
    columns:
      - name: customer_id
        description: Primary key for customers.
        tests:
          - unique
          - not_null

  - name: stg_orders
    description: Staged order data from Snowflake.
    columns:
      - name: order_id
        description: Primary key for orders.
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  - name: stg_payments
    description: Staged payment data from Snowflake.
    columns:
      - name: payment_id
        description: Primary key for payments.
        tests:
          - unique
          - not_null
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']

  - name: fct_orders
    description: Fact table for orders.
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id

  - name: dim_customers
    description: Dimension table for customers.
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
